## Experiment 1

In [1]:
import pandas as pd

In [3]:
df1=pd.read_csv("/student_info.csv")
df1

   Student ID     Name  Age Grade
0         101    Alice   20     A
1         102      Bob   21     B
2         103  Charlie   19     A
3         104    David   22     C
4         105      Eve   20     B

In [5]:
df2=pd.read_csv("/student_workshop_dataset.csv",delimiter="\t")
df2

    Unnamed: 0  roll     name class  marks   age
0            0     1     anil    TE  56.77  22.0
1            1     2     amit    TE  59.77  21.0
2            2     3   aniket    BE  76.88  19.0
3            3     4  ajinkya    TE  69.66  20.0
4            4     5     asha    TE  63.28   NaN
5            5     6   ayesha    BE    NaN  20.0
6            6     7     amar    BE  65.34  19.0
7            7     8    Amita    be  68.33  23.0
8            8     9     amol    TE  56.75  20.0
9            9     9     amol    TE  56.75  20.0
10          10    10    anmol    BE  78.66   NaN
11          11    11   surbhi    TE    NaN  23.0
12          12    12    Sujay    TE  74.12  22.0
13          13    13  subhash    be  88.45  21.0
14          14    14   sachin   NaN  59.33  21.0
15          15    15  shalini    TE  63.45  20.0

In [7]:
df2.rename(columns={'class':'Grade','age':'Age'},inplace=True)

In [9]:
df1.merge(df2,on='Age', how='outer')

,Student ID,Name,Age,Grade_x,Unnamed: 0,roll,name,Grade_y,marks
0,101.0,Alice,20.0,A,3,4,ajinkya,TE,69.66
1,101.0,Alice,20.0,A,5,6,ayesha,BE,NaN
2,101.0,Alice,20.0,A,8,9,amol,TE,56.75
3,101.0,Alice,20.0,A,9,9,amol,TE,56.75
4,101.0,Alice,20.0,A,15,15,shalini,TE,63.45
5,105.0,Eve,20.0,B,3,4,ajinkya,TE,69.66
6,105.0,Eve,20.0,B,5,6,ayesha,BE,NaN
7,105.0,Eve,20.0,B,8,9,amol,TE,56.75
8,105.0,Eve,20.0,B,9,9,amol,TE,56.75
9,105.0,Eve,20.0,B,15,15,shalini,TE,63.45
10,102.0,Bob,21.0,B,1,2,amit,TE,59.77
11,102.0,Bob,21.0,B,13,13,subhash,be,88.45
12,102.0,Bob,21.0,B,14,14,sachin,NaN,59.33
13,103.0,Charlie,19.0,A,2,3,aniket,BE,76.88
14,103.0,Charlie,19.0,A,6,7,amar,BE,65.34
15,104.0,David,22.0,C,0,1,anil,TE,56.77
16,104.0,David,22.0,C,12,12,Sujay,TE,74.12
17,NaN,NaN,NaN,NaN,4,5,asha,TE,63.28
18,NaN,NaN,NaN,NaN,10,10,anmol,BE,78.66
19,NaN,NaN,23.0,NaN,7,8,Amita,be,68.33
20,NaN,NaN,23.0,NaN,11,11,surbhi,TE,NaN

In [10]:
pd.concat([df1,df2])

    Student ID     Name   Age Grade  Unnamed: 0  roll     name  marks
0        101.0    Alice  20.0     A         NaN   NaN      NaN    NaN
1        102.0      Bob  21.0     B         NaN   NaN      NaN    NaN
2        103.0  Charlie  19.0     A         NaN   NaN      NaN    NaN
3        104.0    David  22.0     C         NaN   NaN      NaN    NaN
4        105.0      Eve  20.0     B         NaN   NaN      NaN    NaN
0          NaN      NaN  22.0    TE         0.0   1.0     anil  56.77
1          NaN      NaN  21.0    TE         1.0   2.0     amit  59.77
2          NaN      NaN  19.0    BE         2.0   3.0   aniket  76.88
3          NaN      NaN  20.0    TE         3.0   4.0  ajinkya  69.66
4          NaN      NaN   NaN    TE         4.0   5.0     asha  63.28
5          NaN      NaN  20.0    BE         5.0   6.0   ayesha    NaN
6          NaN      NaN  19.0    BE         6.0   7.0     amar  65.34
7          NaN      NaN  23.0    be         7.0   8.0    Amita  68.33
8          NaN      NaN  20.0    TE         8.0   9.0     amol  56.75
9          NaN      NaN  20.0    TE         9.0   9.0     amol  56.75
10         NaN      NaN   NaN    BE        10.0  10.0    anmol  78.66
11         NaN      NaN  23.0    TE        11.0  11.0   surbhi    NaN
12         NaN      NaN  22.0    TE        12.0  12.0    Sujay  74.12
13         NaN      NaN  21.0    be        13.0  13.0  subhash  88.45
14         NaN      NaN  21.0   NaN        14.0  14.0   sachin  59.33
15         NaN      NaN  20.0    TE        15.0  15.0  shalini  63.45